CREATE DATABASE lv_safety_verification;
use lv_safety_verification;


-----------> LPS <----------

			CREATE TABLE basic_lps_table(
						BASIC_LPS_ID INT AUTO_INCREMENT,
						CLIENT_NAME VARCHAR(225),
						PROJECT_NAME VARCHAR(225),
						PMC_NAME VARCHAR(225),
						CONSULTANT_NAME VARCHAR(225),
						CONTRACTOR_NAME VARCHAR(225),
						DEALER_CONTRACTOR VARCHAR(225),
						ADDRESS VARCHAR(225),
						LOCATION VARCHAR(225),
						INSPECTOR_NAME VARCHAR(225),
						VIEWER_NAME VARCHAR(225),
						COMPANY VARCHAR(225),
						DESIGNATION VARCHAR(225),
						CONTACT_NUMBER VARCHAR(225),
						MAIL_ID VARCHAR(225),
						PREVIOUS_REPORT VARCHAR(20),					
						INDUSTRY_TYPE VARCHAR(225),
						SOIL_RESISTIVITY VARCHAR(225),
						USER_NAME VARCHAR(225),
						ALL_STEPS_COMPLETED VARCHAR(20),
						STATUS VARCHAR(50),
						CREATED_BY VARCHAR(255),
					    CREATED_DATE datetime,
					    UPDATED_BY VARCHAR(255),
			            UPDATED_DATE datetime,
                        FILE_ID INT,
						CONSTRAINT PK_BASIC_LPS_ID PRIMARY KEY(BASIC_LPS_ID)
			);
			
			
	-----------> LPS AIR-TERMINALS <----------	
		  CREATE TABLE air_termination_details_table(
		  		  AIR_TERMINATION_DETAILS_ID INT AUTO_INCREMENT,
		  		  USER_NAME VARCHAR(225),
                  BASIC_LPS_ID INT,               
                  CREATED_BY VARCHAR(255),
			      CREATED_DATE datetime,
				  UPDATED_BY VARCHAR(255),
			      UPDATED_DATE datetime,
                  CONSTRAINT PK_AIR_TERMINATION_DETAILS_ID PRIMARY KEY(AIR_TERMINATION_DETAILS_ID)
		  		 	              
		  );
		  
          CREATE TABLE lpsairdescription_table(
                  LPSAIRDESCRIPTION_ID INT AUTO_INCREMENT,
                  AIR_TERMINATION_DETAILS_ID INT,
                  BUILDING_NUMBER INT,
	              BUILDING_NAME VARCHAR(255),
	              BUILDING_COUNT INT NOT NULL,		
	              BUILDING_TYPE VARCHAR(255),
	              BUILDING_TYPE_OTHERS VARCHAR(255),
	              BUILDING_LENGTH FLOAT,
	              BUILDING_WIDTH FLOAT,
	              BUILDING_HEIGHT FLOAT,
	              PROTECTION_LEVEL VARCHAR(255),
	              PROTRUSION_HEIGHT FLOAT,
	              AIR_BASIC_AVAILABILITY_OB VARCHAR(255),
	              AIR_VERTICAL_TERMINAL_AVAILABILITY_OB VARCHAR(255),
	              AIR_CLAMPS_AVAILABILITY_OB VARCHAR(255),
	              AIR_CONNECTORS_AVAILABILITY_OB VARCHAR(255),
	              AIR_EXPANSION_AVAILABILITY_OB VARCHAR(255),
	              AIR_HOLDER_AVAILABILITY_OB VARCHAR(255),
	              AIR_MESH_AVAILABILITY_OB VARCHAR(255),
	              AIR_BASIC_AVAILABILITY_REM VARCHAR(500),
	              AIR_VERTICAL_TERMINAL_AVAILABILITY_REM VARCHAR(500),
	              AIR_CLAMPS_AVAILABILITY_REM VARCHAR(500),
	              AIR_CONNECTORS_AVAILABILITY_REM VARCHAR(500),
	              AIR_EXPANSION_AVAILABILITY_REM VARCHAR(500),
	              AIR_HOLDER_AVAILABILITY_REM VARCHAR(500),
	              AIR_MESH_AVAILABILITY_REM VARCHAR(500),
	              FLAG VARCHAR(20),
                  CONSTRAINT PK_LPSAIRDESCRIPTION_ID PRIMARY KEY(LPSAIRDESCRIPTION_ID),
                  CONSTRAINT FK_LPSAIRDESCRIPTION_AIR_TERMINATION_DETAILS_ID FOREIGN KEY(AIR_TERMINATION_DETAILS_ID) REFERENCES air_termination_details_table(AIR_TERMINATION_DETAILS_ID) ON DELETE CASCADE
                  
);

		  

		  CREATE TABLE air_basic_description_table(
					AIR_BASIC_DESCRIPTION_ID INT AUTO_INCREMENT,
					LPSAIRDESCRIPTION_ID INT,
					FLAG VARCHAR(20),
					CONSULTANT_NAME_OBSERVATION VARCHAR(225),
					CONSULTANT_NAME_REMARKS VARCHAR(500),
					ARCHITECT_NAMEINOBSERVATION VARCHAR(225),
					ARCHITECT_NAMEINREMARKS VARCHAR(500),
					DATE_OF_DESIGN_OBSERVATION VARCHAR(225),
					DATE_OF_DESIGN_REMARKS VARCHAR(500),
				    OBSERVATION_APPROVED_BY VARCHAR(225),
					REMARKS_APPROVED_BY VARCHAR(500),
					DATEOF_APPROVAL_OB VARCHAR(225),
					DATEOF_APPROVAL_REM VARCHAR(500),
					OBSERVATION_DRAWING_NUMBER VARCHAR(225),
					REMARKS_DRAWING_NUMBER VARCHAR(500),
					OBSERVATION_REVISION_NUMBER VARCHAR(225),
					REMARKS_REVISION_NUMBER VARCHAR(500),
					OBSERVATION_DEVIATION_CHECKING VARCHAR(225),
					REMARKS_DEVIATION_CHECKING VARCHAR(500),
					DEVIATION_INSTALLATION_OBSERVATION VARCHAR(225),
					DEVIATION_INSTALLATION_REMARKS VARCHAR(500),
					COMPANY_NAME_OBSERVATION VARCHAR(225),
					COMPANY_NAME_REMARKS VARCHAR(500),					
					CONNECTION_MADE_BRAZINGOBSERVATION VARCHAR(225),
	                CONNECTION_MADE_BRAZINGREMARKS VARCHAR(500),
	                ELECTRICAL_EQUIPMENT_PLACEDOBSERVATION VARCHAR(225),
	                ELECTRICAL_EQUIPMENT_PLACEDREMARKS VARCHAR(500),
	                COMBUSTABLE_PARTOBSERVATION VARCHAR(225),
	                COMBUSTABLE_PARTREMARKS VARCHAR(500),
	                TERMINATION_MESH_CONDUCTOROBSERVATION VARCHAR(225),
	                TERMINATION_MESH_CONDUCTORREMARKS VARCHAR(500),
	                BONDING_EQUIPOTENTIALOBSERVATION VARCHAR(225),
	                BONDING_EQUIPOTENTIALREMARKS VARCHAR(500),
	                FILE_NAME VARCHAR(225),
	                FILE_TYPE VARCHAR(225),
	                FILE_SIZE VARCHAR(225),
	                FILE_Id INT,
	                FILE_INDEX INT,
	               	CONSTRAINT PK_AIR_BASIC_DESCRIPTION_ID PRIMARY KEY(AIR_BASIC_DESCRIPTION_ID),
	                CONSTRAINT FK_BASICDESCRIPTION_LPSAIRDESCRIPTION_ID FOREIGN KEY(LPSAIRDESCRIPTION_ID) REFERENCES lpsairdescription_table(LPSAIRDESCRIPTION_ID) ON DELETE CASCADE
			);
		

          CREATE TABLE lpsverticalairterminal_table(
                  LPSVERTICALAIRTERMINAL_ID INT AUTO_INCREMENT,
                  LPSAIRDESCRIPTION_ID INT,
				  FLAG VARCHAR(20),
                  PHYSICAL_INSPECTIONOBSERVATION VARCHAR(225),
                  PHYSICAL_INSPECTIONREMARKS VARCHAR(500),
                  TOTAL_NUMBEROBSERVATION  INT,
                  TOTAL_NUMBERREMARKS  VARCHAR(500),
                  INSP_NO_OBS INT,
                  INSP_NO_REM VARCHAR(500),
                  INSP_PASSED_NO_OBS INT,
                  INSP_PASSED_NO_REM VARCHAR(500),
                  INSP_FAILED_NO_OBS INT,
                  INSP_FAILED_NO_REM VARCHAR(500),
                  FILE_NAME_VAIR VARCHAR(250),
                  FILE_TYPE_VAIR VARCHAR(250),
                  FILE_SIZE VARCHAR(225),
                  FILE_ID_VAIR INT,
                  FILE_INDEX_VAIR INT,
                  CONSTRAINT PK_LPSVERTICALAIRTERMINAL_ID  PRIMARY KEY(LPSVERTICALAIRTERMINAL_ID),
                  CONSTRAINT FK_LPSAIRDESCRIPTION_ID FOREIGN KEY(LPSAIRDESCRIPTION_ID) REFERENCES lpsairdescription_table(LPSAIRDESCRIPTION_ID) ON DELETE CASCADE
);

		
		          CREATE TABLE vertical_air_terminal_list_table(
                  VERTICALAIRTERMINALLIST_ID INT AUTO_INCREMENT,
                  LPSVERTICALAIRTERMINAL_ID INT,
                  FLAG VARCHAR(20),              
                  MATERIAL_OF_TERMINALOBSERVATION  VARCHAR(225),
                  MATERIAL_OF_TERMINALREMARKS  VARCHAR(500),
                  SIZE_OF_TERMINALOBSERVATION   VARCHAR(225),
                  SIZE_OF_TERMINALREMARKS   VARCHAR(500),   
                  HEIGHT_OF_TERMINALOBSERVATION  INT,
                  HEIGHT_OF_TERMINALREMARKS   VARCHAR(500),
                  ANGLEPROTECTION_HEIGHTOBSERVATION VARCHAR(225),
                  ANGLEPROTECTION_HEIGHTREMARKS   VARCHAR(500),
                  INSTALLATION_TERMINATIONSYSTEM_OB  VARCHAR(225),
                  INSTALLATION_TERMINATIONSYSTEM_REM  VARCHAR(500),
                  SUPPORT_FLATSURFACEOBSERVATION  VARCHAR(225),
                  SUPPORT_FLATSURFACEREMARKS  VARCHAR(500),
                  HEIGHT_FLATSURAFACEOBSERVATION  VARCHAR(225),
                  HEIGHT_FLATSURAFACEREMARKS  VARCHAR(500),
                  CONSTRAINT PK_VERTICALAIRTERMINALLIST_ID  PRIMARY KEY(VERTICALAIRTERMINALLIST_ID),
                  CONSTRAINT FK_VERTICALAIRTERMINALLIST_LPSVERTICALAIRTERMINAL_ID FOREIGN KEY(LPSVERTICALAIRTERMINAL_ID) REFERENCES lpsverticalairterminal_table(LPSVERTICALAIRTERMINAL_ID) ON DELETE CASCADE
);

          CREATE TABLE air_meshdescription_table(
                  MESHDESCRIPTION_ID INT AUTO_INCREMENT,
                  LPSAIRDESCRIPTION_ID INT,
				  FLAG VARCHAR(20),
                  PHYSICAL_INSPECTION_OB VARCHAR(225),
                  PHYSICAL_INSPECTION_REM VARCHAR(500),
                  MATERIAL_OFCONDUCTOR_OB VARCHAR(225),
                  MATERIAL_OFCONDUCTOR_REM VARCHAR(500),
                  SIZE_OF_CONDUCTOROBSERVATION VARCHAR(225),
                  SIZE_OF_CONDUCTORREMARKS VARCHAR(500),
                  MESH_SIGEOBSERVATION VARCHAR(225),
                  MESH_SIGEREMARKS VARCHAR(500),
                  MAXIMUM_DISTANCE_X_OBSERVATION INT,
                  MAXIMUM_DISTANCE_X_REMARKS VARCHAR(500),
                  MAXIMUM_DISTANCE_Y_OBSERVATION INT,
                  MAXIMUM_DISTANCE_Y_REMARKS VARCHAR(500),
                  MINIMUM_DISTANCE_X_OBSERVATION INT,
                  MINIMUM_DISTANCE_X_REMARKS VARCHAR(500),
                  MINIMUM_DISTANCE_Y_OBSERVATION INT,
                  MINIMUM_DISTANCE_Y_REMARKS VARCHAR(500),
                  HEIGHT_OFCONDUCTOR_FLATSURAFACEOBSERVATION  INT,
                  HEIGHT_OFCONDUCTOR_FLATSURAFACEREMARKS VARCHAR(500),
                  CONSTRAINT PK_MESHDESCRIPTION_ID   PRIMARY KEY(MESHDESCRIPTION_ID),
                  CONSTRAINT FK_MESHDESCRIPTION_LPSAIRDESCRIPTION_ID FOREIGN KEY(LPSAIRDESCRIPTION_ID) REFERENCES lpsairdescription_table(LPSAIRDESCRIPTION_ID) ON DELETE CASCADE
);


          CREATE TABLE air_holders_description_table(
                  HOLDERS_DESCRIPTION_ID INT AUTO_INCREMENT,
                  LPSAIRDESCRIPTION_ID INT,                  
				  FLAG VARCHAR(20),
                  PHYSICAL_INSPECTION_OBSERVATION VARCHAR(225),
                  PHYSICAL_INSPECTION_REMARKS VARCHAR(500),
                  CONDUCTORHOLDER_FLATSURAFACE_OBSERVATION  VARCHAR(225),
                  CONDUCTORHOLDER_FLATSURAFACE_REMARKS VARCHAR(500),
                  CODUCTOR_HOLDER_OBSERVATION VARCHAR(225),
                  CODUCTOR_HOLDER_REMARKS VARCHAR(500),
                  MATERIAL_OFPARPET_HOLDEROB VARCHAR(225),
                  MATERIAL_OFPARPET_HOLDERREM VARCHAR(500),
                  TOTALPARPET_HOLDER_OBSERVATION INT,
                  TOTALPARPET_HOLDER_REMARKS VARCHAR(500),
                  PH_INSP_NO_OBS INT,
                  PH_INSP_NO_REM VARCHAR(500),
                  PH_INSP_PASSED_NO_OBS INT,
                  PH_INSP_PASSED_NO_REM VARCHAR(500),
                  PH_INSP_FAILED_NO_OBS INT,
                  PH_INSP_FAILED_NO_REM VARCHAR(500),
                  CONSTRAINT PK_HOLDERS_DESCRIPTION_ID   PRIMARY KEY(HOLDERS_DESCRIPTION_ID ),
                  CONSTRAINT FK_HOLDERS_DESCRIPTION_LPSAIRDESCRIPTION_ID FOREIGN KEY(LPSAIRDESCRIPTION_ID) REFERENCES lpsairdescription_table(LPSAIRDESCRIPTION_ID) ON DELETE CASCADE
);


			CREATE TABLE air_holders_list_table(
                  HOLDERS_LIST_ID INT AUTO_INCREMENT,
                  HOLDERS_DESCRIPTION_ID INT,                  
                  FLAG VARCHAR(20),
                  HOLDER_TYPE_OBSERVATION VARCHAR(225),
                  HOLDER_TYPE_REMARKS VARCHAR(500),
                  MATERIAL_HOLDER_OBSERVATION VARCHAR(225),
                  MATERIAL_HOLDER_REMARKS VARCHAR(500),
                  TOTAL_HOLDERSNO_OBSERVATION INT,
                  TOTAL_HOLDERSNO_REMARKS VARCHAR(500),
                  HO_INSP_NO_OBS INT,
                  HO_INSP_NO_REM VARCHAR(500),
                  HO_INSP_PASSED_NO_OBS INT,
                  HO_INSP_PASSED_NO_REM VARCHAR(500),
                  HO_INSP_FAILED_NO_OBS INT,
                  HO_INSP_FAILED_NO_REM VARCHAR(500),
                  CONSTRAINT PK_HOLDERS_LIST_ID   PRIMARY KEY(HOLDERS_LIST_ID),
                  CONSTRAINT FK_HOLDERS_LIST_HOLDERS_DESCRIPTION_ID FOREIGN KEY(HOLDERS_DESCRIPTION_ID) REFERENCES air_holders_description_table(HOLDERS_DESCRIPTION_ID) ON DELETE CASCADE
);


          CREATE TABLE air_clamps_table(
                  CLAMPS_ID INT AUTO_INCREMENT,
                  LPSAIRDESCRIPTION_ID INT,
				  FLAG VARCHAR(20),
                  PHYSICAL_INSPECTION_OBSERVATION VARCHAR(225),
                  PHYSICAL_INSPECTION_REMARKS VARCHAR(500),
                  CONDUCTORCLAMPS_FLATSURAFACE_OBSERVATION VARCHAR(225),
                  CONDUCTORCLAMPS_FLATSURAFACE_REMARKS VARCHAR(500),
                  INTERCONNECTION_OF_CLAMPS_OBSERVATION VARCHAR(225),
                  INTERCONNECTION_OF_CLAMPS_REMARKS VARCHAR(500),
                  CLAMP_TYPE_OBSERVATION VARCHAR(225),
                  CLAMP_TYPE__REMARKS VARCHAR(500),
                  MATERIAL_OF_WALL_CLAMPS_OBSERVATION VARCHAR(225),
                  MATERIAL_OF_WALL_CLAMPS_REMARKS VARCHAR(500),
                  MATERIAL_OF_FOLDING_CLAMPS_OBSERVATION VARCHAR(225),
                  MATERIAL_OF_FOLDING_CLAMPS_REMARKS VARCHAR(500),
                  TOTAL_CLAMPSNO_OBSERVATION INT,
                  TOTAL_CLAMPSNO_REMARKS VARCHAR(500),
                  INSP_NO_OBS INT,
                  INSP_NO_REM VARCHAR(500),
                  INSP_PASSED_NO_OBS INT,
                  INSP_PASSED_NO_REM VARCHAR(500),
                  INSP_FAILED_NO_OBS INT,
                  INSP_FAILED_NO_REM VARCHAR(500),
                  CONSTRAINT PK_CLAMPS_ID PRIMARY KEY(CLAMPS_ID),
                  CONSTRAINT FK_CLAMPS_LPSAIRDESCRIPTION_ID FOREIGN KEY(LPSAIRDESCRIPTION_ID) REFERENCES lpsairdescription_table(LPSAIRDESCRIPTION_ID) ON DELETE CASCADE
);


         CREATE TABLE air_expansion_table(
                  EXPANSION_ID INT AUTO_INCREMENT,
                  LPSAIRDESCRIPTION_ID INT,
				  FLAG VARCHAR(20),
                  PHYSICAL_INSPECTION_OBSERVATION VARCHAR(225),
                  PHYSICAL_INSPECTION_REMARKS VARCHAR(500),
                  STRIGHTCONNECTOR_PIECS_OBSERVATION  VARCHAR(225),
                  STRIGHTCONNECTOR_PIECS_REMARKS  VARCHAR(500),
                  MATERIAL_OF_CONNECTOR_OBSERVATION  VARCHAR(225),
                  MATERIAL_OF_CONNECTOR_REMARKS VARCHAR(500),
                  MATERIAL_OF_EXPANSIONPIECE_OBSERVATION  VARCHAR(225),
                  MATERIAL_OF_EXPANSIONPIECE_REMARKS VARCHAR(500),
                  INTERVAL_BETWEEN_EXPANSION_OBSERVATION INT,
                  INTERVAL_BETWEEN_EXPANSION_REMARKS VARCHAR(500),
                  TOTALNO_EXPANSIONPIECE_OBSERVATION INT,
                  TOTALNO_EXPANSIONPIECE_REMARKS VARCHAR(500),
                  INSP_NO_OBS INT,
                  INSP_NO_REM VARCHAR(500),
                  INSP_PASSED_NO_OBS INT,
                  INSP_PASSED_NO_REM VARCHAR(500),
                  INSP_FAILED_NO_OBS INT,
                  INSP_FAILED_NO_REM VARCHAR(500),
                  FILE_NAME_EP VARCHAR(250),
                  FILE_TYPE_EP VARCHAR(250),
                  FILE_SIZE VARCHAR(225),
                  FILE_ID_EP INT,
                  FILE_INDEX_EP INT,
                  CONSTRAINT PK_EXPANSION_ID PRIMARY KEY(EXPANSION_ID),
                  CONSTRAINT FK_EXPANSION_LPSAIRDESCRIPTION_ID FOREIGN KEY(LPSAIRDESCRIPTION_ID) REFERENCES lpsairdescription_table(LPSAIRDESCRIPTION_ID) ON DELETE CASCADE
);



           CREATE TABLE air_connectors_table(
                   CONNECTORS_ID INT AUTO_INCREMENT,
                   LPSAIRDESCRIPTION_ID INT,
				   FLAG VARCHAR(20),
                   PHYSICAL_INSPECTION_OBSERVATION VARCHAR(225),
                   PHYSICAL_INSPECTION_REMARKS VARCHAR(500),
                   CHECKCONNECTION_CONNECTORS_OBSERVATION VARCHAR(225),
                   CHECKCONNECTION_CONNECTORS_REMARKS VARCHAR(500),
                   MATERIAL_OF_CONNECTORS_OBSERVATION VARCHAR(225),
                   MATERIAL_OF_CONNECTORS_REMARKS VARCHAR(500),
                   STRIGHT_CONNECTORS_OBSERVATION VARCHAR(225),
                   STRIGHT_CONNECTORS_REMARKS VARCHAR(500),
                   T_CONNECTORS_OBSERVATION VARCHAR(225),
                   T_CONNECTORS_REMARKS VARCHAR(500),
                   L_CONNECTORS_OBSERVATION VARCHAR(225),
                   L_CONNECTORS_REMARKS VARCHAR(500),
                   TOTALNO_CONNECTORS_OBSERVATION INT,
                   TOTALNO_CONNECTORS_REMARKS VARCHAR(500),
                   INSP_NO_OBS INT,
                   INSP_NO_REM VARCHAR(500),
                   INSP_PASSED_NO_OBS INT,
                   INSP_PASSED_NO_REM VARCHAR(500),
                   INSP_FAILED_NO_OBS INT,
                   INSP_FAILED_NO_REM VARCHAR(500),
                   CONSTRAINT PK_CONNECTORS_ID PRIMARY KEY(CONNECTORS_ID),
                   CONSTRAINT FK_CONNECTORS_LPSAIRDESCRIPTION_ID FOREIGN KEY(LPSAIRDESCRIPTION_ID) REFERENCES lpsairdescription_table(LPSAIRDESCRIPTION_ID) ON DELETE CASCADE
);

			
                 
                 
        -----------> LPS DOWN-CONDUCTOR <----------	      
        
        	CREATE TABLE down_conductor_report_table(
                          DOWN_CONDUCTOR_REPORT_ID INT AUTO_INCREMENT,
                          BASIC_LPS_ID INT,
                          USER_NAME VARCHAR(225),
                          CREATED_BY VARCHAR(255),
                          CREATED_DATE datetime,
                          UPDATED_BY VARCHAR(255),
                          UPDATED_DATE datetime,                          
                          CONSTRAINT PK_DOWN_CONDUCTOR_REPORT_ID PRIMARY KEY(DOWN_CONDUCTOR_REPORT_ID)
);   
                 
                 
             CREATE TABLE downconductordescription_table(
                          DOWNCONDUCTORDESCRIPTION_ID INT AUTO_INCREMENT,
                          DOWN_CONDUCTOR_REPORT_ID INT,
                          BUILDING_NUMBER INT,
			              BUILDING_NAME VARCHAR(255),
			              BUILDING_COUNT INT NOT NULL,	
                          FLAG VARCHAR(20),
                          BI_METALLICISSUE_OB VARCHAR(225),
                          BI_METALLICISSUE_REM VARCHAR(500),
                          WARNINGNOTICE_GROUNDLEVEL_OB VARCHAR(225),
                          WARNINGNOTICE_GROUNDLEVEL_REM VARCHAR(500),
                          INSULATION_PRESENCE_OB VARCHAR(225),
                          INSULATION_PRESENCE_REM VARCHAR(500),
                          NOPOWER_DOWNCONDUCTOR_OB VARCHAR(225),
                          NOPOWER_DOWNCONDUCTOR_REM VARCHAR(500),
                          CONNECTIONSMADE_BY_BRAZING_OB VARCHAR(225),
                          CONNECTIONSMADE_BY_BRAZING_REM VARCHAR(500),
                          CHEMICAL_SPRINKLER_OB VARCHAR(225),
                          CHEMICAL_SPRINKLER_REM VARCHAR(500),
                          COMBUSTIBLEMATERIAL_WALL_OB VARCHAR(225),
                          COMBUSTIBLEMATERIAL_WALL_REM VARCHAR(500),    
                          BRIDGING_DESC_AVAILABILITY_OB VARCHAR(225),
                          BRIDGING_DESC_AVAILABILITY_REM VARCHAR(500),
                          HOLDER_AVAILABILITY_OB VARCHAR(225),
                          HOLDER_AVAILABILITY_REM VARCHAR(500),                         
                          CONNECTORS_AVAILABILITY_OB VARCHAR(225),
                          CONNECTORS_AVAILABILITY_REM VARCHAR(500),                         
                          LIGHTNING_COUNTERS_AVAILABILITY_OB VARCHAR(225),
                          LIGHTNING_COUNTERS_AVAILABILITY_REM VARCHAR(500),                          
                          TESTING_JOINT_AVAILABILITY_OB VARCHAR(225),
                          TESTING_JOINT_AVAILABILITY_REM VARCHAR(500),                         
                          DOWNCONDUCTOR_AVAILABILITY_OB VARCHAR(225),
                          DOWNCONDUCTOR_AVAILABILITY_REM VARCHAR(500),                         
                          DOWNCONDUCTOR_TESTING_AVAILABILITY_OB VARCHAR(225),
                          DOWNCONDUCTOR_TESTING_AVAILABILITY_REM VARCHAR(500),
                          ITR_INDEX INT,
                          FILE_NAME1 VARCHAR(500),
						  FILE_TYPE1 VARCHAR(500),
						  FILE_ID1 INT,
						  FILE_SIZE VARCHAR(225),
                          CONSTRAINT PK_DOWNCONDUCTORDESCRIPTION_ID PRIMARY KEY(DOWNCONDUCTORDESCRIPTION_ID),
              			  CONSTRAINT FK_DOWN_CONDUCTOR_REPORT_DOWNCONDUCTORDESCRIPTION_ID FOREIGN KEY(DOWN_CONDUCTOR_REPORT_ID) REFERENCES down_conductor_report_table(DOWN_CONDUCTOR_REPORT_ID) ON DELETE CASCADE
                          
);


		   CREATE TABLE downconductor_table(
						DOWNCONDUCTOR_ID INT AUTO_INCREMENT,
						DOWNCONDUCTORDESCRIPTION_ID INT,
                        FLAG VARCHAR(20),
						PHYSICAL_INSPECTION_OB VARCHAR(225),
						PHYSICAL_INSPECTION_REM VARCHAR(500),
						CONDUCTOR_MATERIAL_OB VARCHAR(225),
						CONDUCTOR_MATERIAL_REM VARCHAR(500),
						CONDUCTOR_SIZE_OB VARCHAR(225),
						CONDUCTOR_SIZE_REM VARCHAR(500),
						DOWNCONDUCTOR_EXPOSED_OB VARCHAR(225),
						DOWNCONDUCTOR_EXPOSED_RE VARCHAR(500),
						DOWNCONDUCTOR_LOCATION_OB VARCHAR(225),
						DOWNCONDUCTOR_LOCATION_REM VARCHAR(500),
						DOWNCONDUCTOR_GUTTERS_OB VARCHAR(225),
						DOWNCONDUCTOR_GUTTERS_REM VARCHAR(500),
						INSTALLED_SHAFT_DOWNCONDUCTOR_OB VARCHAR(225),
						INSTALLED_SHAFT_DOWNCONDUCTOR_REM VARCHAR(500),
						ENSURE_DOWNCONDUCTOR_OB VARCHAR(225),
						ENSURE_DOWNCONDUCTOR_REM VARCHAR(500),
						INSTALLATION_DOWNCONDUCTOR_OB VARCHAR(225),
						INSTALLATION_DOWNCONDUCTOR_REM VARCHAR(500),
						MAXIMUM_DOWNCONDUCTOR_OB FLOAT,
						MAXIMUM_DOWNCONDUCTOR_REM VARCHAR(500),
						MINIMUM_DOWNCONDUCTOR_OB FLOAT,
						MINIMUM_DOWNCONDUCTOR_REM VARCHAR(500),
						TOTALNO_DOWNCONDUCTOR_OB INT,
						TOTALNO_DOWNCONDUCTOR_REM VARCHAR(500),
						INSPECTED_NO_OB INT,
						INSPECTED_NO_REM VARCHAR(500),
						INSPECTIONSPASSED_NO_OB INT,
						INSPECTIONSPASSED_NO_REM VARCHAR(500),
						INSPECTIONFAILED_NO_OB INT,
						INSPECTIONFAILED_NO_REM VARCHAR(500),
						AVG_DANGEROUS_BENDS_OB INT,
						AVG_DANGEROUS_BENDS_REM VARCHAR(500),
						TYPE_NATURAL_DOWN_CONDUCTORS_OB VARCHAR(225),
						TYPE_NATURAL_DOWN_CONDUCTORS_REM VARCHAR(500),
						NATURAL_DOWN_CONDUCTORS_DIMENSION_OB VARCHAR(225),
						NATURAL_DOWN_CONDUCTORS_DIMENSION_REM VARCHAR(500),
					    ITR_INDEX INT,
						FILE_NAME VARCHAR(500),
						FILE_TYPE VARCHAR(500),
						FILE_SIZE VARCHAR(225),
						FILE_ID INT,
						CONSTRAINT PK_DOWNCONDUCTOR_ID PRIMARY KEY(DOWNCONDUCTOR_ID),
						CONSTRAINT FK_DOWNCONDUCTOR_ID FOREIGN KEY(DOWNCONDUCTORDESCRIPTION_ID) REFERENCES downconductordescription_table(DOWNCONDUCTORDESCRIPTION_ID) ON DELETE CASCADE
);


           CREATE TABLE bridgingdescription_table(
						BRIDGINGDESCRIPTION_ID INT AUTO_INCREMENT,
						DOWNCONDUCTORDESCRIPTION_ID INT,
						FLAG VARCHAR(20),
						ENSURE_BRIDGINGCABLE_OB VARCHAR(225),
						ENSURE_BRIDGINGCABLE_REM VARCHAR(500),
						ALUMINIUMCONDUCTOR_SIDEWALL_OB VARCHAR(225),
						ALUMINIUMCONDUCTOR_SIDEWALL_REM VARCHAR(500),
						BRIDGINGCABLE_CONNECTION_OB VARCHAR(225),
						BRIDGINGCABLE_CONNECTION_REM VARCHAR(500),
						BRIDGINGCABLE_MATERIAL_OB VARCHAR(225),
						BRIDGINGCABLE_MATERIAL_REM VARCHAR(500),
						BRIDGINGCABLE_SIZE_OB VARCHAR(225),
						BRIDGINGCABLE_SIZE_REM VARCHAR(500),
						TOTALNO_BRIDGINGCABLE_OB INT,
						TOTALNO_BRIDGINGCABLE_REM VARCHAR(500),
						INSPECTED_NO_OB INT,
						INSPECTED_NO_REM VARCHAR(500),
						INSPECTIONSPASSED_NO_OB INT,
						INSPECTIONSPASSED_NO_REM VARCHAR(500),
						INSPECTIONFAILED_NO_OB INT,
						INSPECTIONFAILED_NO_REM VARCHAR(500),
						
						CONSTRAINT PK_BRIDGINGDESCRIPTION_ID PRIMARY KEY(BRIDGINGDESCRIPTION_ID ),
						CONSTRAINT FK_DOWNCONDUCTORDESCRIPTION_ID FOREIGN KEY(DOWNCONDUCTORDESCRIPTION_ID) REFERENCES downconductordescription_table(DOWNCONDUCTORDESCRIPTION_ID) ON DELETE CASCADE
);


           CREATE TABLE holders_table(
						HOLDERS_ID INT AUTO_INCREMENT,
						DOWNCONDUCTORDESCRIPTION_ID INT,
                        FLAG VARCHAR(20),
						PHYSICAL_INSPECTION_OB VARCHAR(225),
						PHYSICAL_INSPECTION_REM VARCHAR(500),
						CONDUCTORHOLDER_FLATSURFACE_OB VARCHAR(225),
						CONDUCTORHOLDER_FLATSURFACE_REM VARCHAR(500),
						CONDUCTOR_HOLDED_OB VARCHAR(225),
						CONDUCTOR_HOLDED_REM VARCHAR(500),
						SUCCESSIVE_DISTANCE_OB FLOAT,
						SUCCESSIVE_DISTANCE_REM VARCHAR(500),
						MATERIAL_HOLDER_OB VARCHAR(225),
						MATERIAL_HOLDER_REM VARCHAR(500),
						TOTALNO_HOLDERS_OB INT,
						TOTALNO_HOLDERS_REM VARCHAR(500),
						INSPECTED_NO_OB INT,
						INSPECTED_NO_REM VARCHAR(500),
						INSPECTIONSPASSED_NO_OB INT,
						INSPECTIONSPASSED_NO_REM VARCHAR(500),
						INSPECTIONFAILED_NO_OB INT,
						INSPECTIONFAILED_NO_REM VARCHAR(500),
						
						CONSTRAINT PK_HOLDERS_ID PRIMARY KEY(HOLDERS_ID),
						CONSTRAINT FK_HOLDERS_DOWNCONDUCTORDESCRIPTION_ID FOREIGN KEY(DOWNCONDUCTORDESCRIPTION_ID) REFERENCES downconductordescription_table(DOWNCONDUCTORDESCRIPTION_ID) ON DELETE CASCADE		
);


           CREATE TABLE connectors_table(
						CONNECTORS_ID INT AUTO_INCREMENT,
						DOWNCONDUCTORDESCRIPTION_ID INT,
                        FLAG VARCHAR(20),
						PHYSICAL_INSPECTION_OB VARCHAR(225),
						PHYSICAL_INSPECTION_REM VARCHAR(500),
						STRAIGHT_CONNECTORCHACK_OB VARCHAR(225),
						STRAIGHT_CONNECTORCHACK_REM VARCHAR(500),
						MATERIAL_CONNECTOR_OB VARCHAR(225),
						MATERIAL_CONNECTOR_REM VARCHAR(500),
						MAXCONNECTORS_DOWNCONDUCTORS_OB INT,
						MAXCONNECTORS_DOWNCONDUCTORS_REM VARCHAR(500),
						TOTALNO_CONNECTORS_OB INT,
						TOTALNO_CONNECTORS_REM VARCHAR(500),
						INSPECTED_NO_OB INT,
						INSPECTED_NO_REM VARCHAR(500),
						INSPECTIONSPASSED_NO_OB INT,
						INSPECTIONSPASSED_NO_REM VARCHAR(500),
						INSPECTIONFAILED_NO_OB INT,
						INSPECTIONFAILED_NO_REM VARCHAR(500),
						
						CONSTRAINT PK_CONNECTORS_ID PRIMARY KEY(CONNECTORS_ID),
						CONSTRAINT FK_CONNECTORS_DOWNCONDUCTORDESCRIPTION_ID FOREIGN KEY(DOWNCONDUCTORDESCRIPTION_ID) REFERENCES downconductordescription_table(DOWNCONDUCTORDESCRIPTION_ID) ON DELETE CASCADE
);

           CREATE TABLE lightningcounters_table(
						LIGHTNINGCOUNTERS_ID INT AUTO_INCREMENT,
						DOWNCONDUCTORDESCRIPTION_ID INT,
                        FLAG VARCHAR(20),
						THREADHOLD_CURRENT_OB FLOAT,
						THREADHOLD_CURRENT_REM VARCHAR(500),
						MAXIMUMWITHSTAND_CURRENT_OB FLOAT,
						MAXIMUMWITHSTAND_CURRENT_REM VARCHAR(500),
						COUNTS_OB INT,
						COUNTS_REM VARCHAR(500),
						BATTERY_LIFETIME_OB INT,
						BATTERY_LIFETIME_REM VARCHAR(500),
						PROPERCONNECTION_LIGHTINGCOUNTER_OB VARCHAR(225),
						PROPERCONNECTION_LIGHTINGCOUNTER_REM VARCHAR(500),
						LIGHTINGCOUNTER_PLACED_OB VARCHAR(225),
						LIGHTINGCOUNTER_PLACED_REM VARCHAR(500),
						CONDITION_OF_LIGHTINGCOUNTER_OB VARCHAR(225),
						CONDITION_OF_LIGHTINGCOUNTER_REM VARCHAR(500),
						TOTALNO_LIGHTNINGCOUNTER_OB INT,
						TOTALNO_LIGHTNINGCOUNTER_REM VARCHAR(500),
						INSPECTED_NO_OB INT,
						INSPECTED_NO_REM VARCHAR(500),
						INSPECTIONSPASSED_NO_OB INT,
						INSPECTIONSPASSED_NO_REM VARCHAR(500),
						INSPECTIONFAILED_NO_OB INT,
						INSPECTIONFAILED_NO_REM VARCHAR(500),
						
						CONSTRAINT PK_LIGHTNINGCOUNTERS_ID PRIMARY KEY(LIGHTNINGCOUNTERS_ID ),
						CONSTRAINT FK_LIGHTNINGCOUNTERS_DOWNCONDUCTORDESCRIPTION_ID FOREIGN KEY(DOWNCONDUCTORDESCRIPTION_ID) REFERENCES downconductordescription_table(DOWNCONDUCTORDESCRIPTION_ID) ON DELETE CASCADE
);


		   CREATE TABLE testjoints_table(
						TESTJOINT_ID INT AUTO_INCREMENT,
						DOWNCONDUCTORDESCRIPTION_ID INT,
						FLAG VARCHAR(20),
						TESTJOINT_TYPE_OB VARCHAR(225),
						TESTJOINT_TYPE_REM VARCHAR(500),
						MATERIAL_TESTJOINT_OB VARCHAR(225),
						MATERIAL_TESTJOINT_REM VARCHAR(500),
						ACCESSIBILITY_OF_TESTJOINT_OB VARCHAR(225),
						ACCESSIBILITY_OF_TESTJOINT_REM VARCHAR(500),
						NONMETALICCASING_PROTECTION_OB VARCHAR(225),
						NONMETALICCASING_PROTECTION_REM VARCHAR(500),
						TESTJOINTPLACED_GROUNTLEVEL_OB VARCHAR(225),
						TESTJOINTPLACED_GROUNTLEVEL_REM VARCHAR(500),
						BIMETALLICISSUE_CHECK_OB VARCHAR(225),
						BIMETALLICISSUE_CHECK_REM VARCHAR(500),
						TOUCHING_CONDUCTORS_OB VARCHAR(225),
						TOUCHING_CONDUCTORS_REM VARCHAR(500),
						TOTALNO_OF_TESTJOINT_OB INT,
						TOTALNO_OF_TESTJOINT_REM VARCHAR(500),
						INSPECTED_NO_OB INT,
						INSPECTED_NO_REM VARCHAR(500),
						INSPECTIONSPASSED_NO_OB INT,
						INSPECTIONSPASSED_NO_REM VARCHAR(500),
						INSPECTIONFAILED_NO_OB INT,
						INSPECTIONFAILED_NO_REM VARCHAR(500),
						
						CONSTRAINT PK_TESTJOINT_ID PRIMARY KEY(TESTJOINT_ID),
						CONSTRAINT FK_TESTJOINTS_DOWNCONDUCTORDESCRIPTION_ID FOREIGN KEY(DOWNCONDUCTORDESCRIPTION_ID) REFERENCES downconductordescription_table(DOWNCONDUCTORDESCRIPTION_ID) ON DELETE CASCADE
);

				CREATE TABLE down_conductor_testing_table(
						DOWN_CONDUCTOR_TESTING_ID INT AUTO_INCREMENT,
						DOWNCONDUCTORDESCRIPTION_ID INT,
                        FLAG VARCHAR(20),
						SERIAL_NUMBER INT,
						REFERENCE VARCHAR(225),
						LENGTH FLOAT,
						RESISTANCE FLOAT,
						REMARKS VARCHAR(500),
						CONSTRAINT PK_DOWN_CONDUCTOR_TESTING_ID PRIMARY KEY(DOWN_CONDUCTOR_TESTING_ID),
						CONSTRAINT FK_DOWN_CONDUCTOR_TESTING_ID FOREIGN KEY(DOWNCONDUCTORDESCRIPTION_ID) REFERENCES downconductordescription_table(DOWNCONDUCTORDESCRIPTION_ID) ON DELETE CASCADE
);








        -----------> LPS EARTHING-TABLE <----------	 
        
        	CREATE TABLE earthing_report_table(
							EARTHING_REPORT_ID INT AUTO_INCREMENT,
							BASIC_LPS_ID INT,
							USER_NAME VARCHAR(225),
							CREATED_BY VARCHAR(255),
							CREATED_DATE datetime,
							UPDATED_BY VARCHAR(255),
							UPDATED_DATE datetime,
							CONSTRAINT PK_EARTHING_REPORT_ID PRIMARY KEY(EARTHING_REPORT_ID)
							);

           	CREATE TABLE earthing_lps_description(
							EARTHING_ID INT AUTO_INCREMENT,
							EARTHING_REPORT_ID INT,
							BUILDING_NUMBER INT,
							BUILDING_NAME VARCHAR(225),
							BUILDING_COUNT INT NOT NULL,	
                            FLAG VARCHAR(20),
							EARTHING_TYPEINOB VARCHAR(225),
							EARTHING_TYPEINREM VARCHAR(500),
							BIMETALLIC_ISSUEINOB VARCHAR(225),
							BIMETALLIC_ISSUEINREM VARCHAR(500),
							BRAZING_CONNECTIONSINOB VARCHAR(225),
							BRAZING_CONNECTIONSINREM VARCHAR(500),	
							EARTHING_DESC_AVAILABILITY_OB VARCHAR(225),
							EARTHING_DESC_AVAILABILITY_REM VARCHAR(500),							
							EARTHING_CLAMPS_AVAILABILITY_OB VARCHAR(225),
							EARTHING_CLAMPS_AVAILABILITY_REM VARCHAR(500),							
							EARTHING_ELECTRODE_CHAMBER_AVAILABILITY_OB VARCHAR(225),
							EARTHING_ELECTRODE_CHAMBER_AVAILABILITY_REM VARCHAR(500),							
							EARTHING_SYSTEM_AVAILABILITY_OB VARCHAR(500),
							EARTHING_SYSTEM_AVAILABILITY_REM VARCHAR(500),						
							EARTHING_ELECTRODE_TESTING_AVAILABILITY_OB VARCHAR(225),						
							EARTHING_ELECTRODE_TESTING_AVAILABILITY_REM	VARCHAR(500),			
							CONSTRAINT PK_EARTHING_ID PRIMARY KEY(EARTHING_ID),
							CONSTRAINT FK_EARTHING_REPORT_EARTHING_ID FOREIGN KEY(EARTHING_REPORT_ID) REFERENCES earthing_report_table(EARTHING_REPORT_ID) ON DELETE CASCADE
							
							);



				CREATE TABLE earthdescription_table(
							EARTHDESCRIPTION_ID INT AUTO_INCREMENT,
							EARTHING_ID INT,
                            FLAG VARCHAR(20),
							SOIL_RESISTIVITYINOB FLOAT,
							SOIL_RESISTIVITYINREM VARCHAR(500),
							EARTHELECTRODE_LESSTHAN_DOWNCONDUCTORSINOB VARCHAR(225),
							EARTHELECTRODE_LESSTHAN_DOWNCONDUCTORSINREM VARCHAR(500),
							CONNECTED_EARTHTERMINATIONINOB VARCHAR(225),
							CONNECTED_EARTHTERMINATIONINREM VARCHAR(500),
							TESTJOINT_EARTHELECTRODEINOB VARCHAR(225),
							TESTJOINT_EARTHELECTRODEINREM VARCHAR(500),
							GROUNTLEVEL_COMPOUNTFILLEDINOB VARCHAR(225),
							GROUNTLEVEL_COMPOUNTFILLEDINREM VARCHAR(500),
							EARTHELECT_MAXIMUMDISTANCEWALLINOB FLOAT,
							EARTHELECT_MAXIMUMDISTANCEWALLINREM VARCHAR(500),
							EARTHELECT_MINIMUMDISTANCEWALLINOB FLOAT,
							EARTHELECT_MINIMUMDISTANCEWALLINREM VARCHAR(500),
							EARTHELECT_MAXIMUMDISTANCEINOB FLOAT,
							EARTHELECT_MAXIMUMDISTANCEINREM VARCHAR(500),
							EARTHELECT_MINIMUMDISTANCEINOB FLOAT,
							EARTHELECT_MINIMUMDISTANCEINREM VARCHAR(500),
							TOTALNUMBER_OF_ELECTRODEINOB INT,
							TOTALNUMBER_OF_ELECTRODEINREM VARCHAR(500),
							INSPECTED_NO_OB INT,
							INSPECTED_NO_REM VARCHAR(500),
							INSPECTIONSPASSED_NO_OB INT,
							INSPECTIONSPASSED_NO_REM VARCHAR(500),
							INSPECTIONFAILED_NO_OB INT,
							INSPECTIONFAILED_NO_REM VARCHAR(500),
							CONSTRAINT PK_EARTHDESCRIPTION_ID PRIMARY KEY(EARTHDESCRIPTION_ID),
							CONSTRAINT FK_EARTHING_ID FOREIGN KEY(EARTHING_ID) REFERENCES earthing_lps_description(EARTHING_ID) ON DELETE CASCADE
							);


				CREATE TABLE earthdescription_list_table(
							EARTHDESCRIPTION_LIST_ID INT AUTO_INCREMENT,
							EARTHDESCRIPTION_ID INT,
                            FLAG VARCHAR(20),
							EARTHING_CONDUCTOR_MATERIAL_OB VARCHAR(225),
							EARTHING_CONDUCTOR_MATERIAL_REM VARCHAR(500),
							EARTHELECTRODE_MATERIALINOB VARCHAR(225),
							EARTHELECTRODE_MATERIALINREM VARCHAR(500),
							EARTHELECTRODE_TYPE_IN_OB VARCHAR(225),
							EARTHELECTRODE_TYPE_IN_REM VARCHAR(500),							
							EARTHELECTRODE_SIZEINOB VARCHAR(225),
							EARTHELECTRODE_SIZEINREM VARCHAR(500),
							EARTHELECTRODE_LENGTHINOB FLOAT,
							EARTHELECTRODE_LENGTHINREM VARCHAR(500),

							CONSTRAINT PK_EARTHDESCRIPTION_LIST_ID PRIMARY KEY(EARTHDESCRIPTION_LIST_ID),
							CONSTRAINT FK_EARTHDESCRIPTION_ID FOREIGN KEY(EARTHDESCRIPTION_ID) REFERENCES earthdescription_table(EARTHDESCRIPTION_ID) ON DELETE CASCADE
							);



				CREATE TABLE earthingclamps_table(
							EARTHCLAMPS_ID INT AUTO_INCREMENT,
							EARTHING_ID INT,
                            FLAG VARCHAR(20),
							PHYSICAL_INSPECTIONINOB VARCHAR(225),
							PSYSICAL_INSPECTIONINREM VARCHAR(500),
							CLAMPS_FIRMLYOB VARCHAR(225),
							CLAMPS_FIRMLYINREM VARCHAR(500),
							INTERCONNECTION_OF_EARTHCLAMPSINOB VARCHAR(225),
							INTERCONNECTION_OF_EARTHCLAMPSINREM VARCHAR(500),
							TYPE_OF_CLAMPSINOB VARCHAR(225),
							TYPE_OF_CLAMPSINREM VARCHAR(500),
							MATERIAL_OF_CLAMPSINOB VARCHAR(225),
							MATERIAL_OF_CLAMPSINREM VARCHAR(500),
							TOTALNO_CLAMPSINOB INT,
							TOTALNO_CLAMPSINREM VARCHAR(500),
							INSPECTED_CLAMPSINOB INT,
							INSPECTED_CLAMPSINREM VARCHAR(500),
							INSPECTED_PASSEDINOB INT,
							INSPECTED_PASSEDINREM VARCHAR(500),
							INSPECTED_FAILEDINOB INT,
							INSPECTED_FAILEDINREM VARCHAR(500),
		
							CONSTRAINT PK_EARTHCLAMPS_ID PRIMARY KEY(EARTHCLAMPS_ID),
							CONSTRAINT FK_EARTHCLAMPS_EARTHING_ID FOREIGN KEY(EARTHING_ID) REFERENCES earthing_lps_description(EARTHING_ID) ON DELETE CASCADE
							);
							




				CREATE TABLE earthelectrodechamber_table(
							EARTHELECTRODECHAMBER_ID INT AUTO_INCREMENT,
							EARTHING_ID INT,
                            FLAG VARCHAR(20),
							PHYSICAL_INSPECTIONOB VARCHAR(225),
							PHYSICAL_INSPECTIONREM VARCHAR(500),
							CHAMBER_TYPEOB VARCHAR(225),
							CHAMBER_TYPEREM VARCHAR(500),
							CHAMBER_SIZEOB VARCHAR(225),
							CHAMBER_SIZEREM VARCHAR(500),
							MAXIMUMWITHSTAND_LOADOB VARCHAR(225),
							MAXIMUMWITHSTAND_LOADREM VARCHAR(500),
							CHAMBER_LOCATION_OB VARCHAR(225),
							CHAMBER_LOCATION_REM VARCHAR(500),
							CHAMBER_PLACED_SOILOB VARCHAR(225),
							CHAMBER_PLACED_SOILREM VARCHAR(500),
							TOTAL_CHAMBERSNOOB INT,
							TOTAL_CHAMBERSNOREM VARCHAR(500),
							INSPECTED_CHAMBERINOB INT,
							INSPECTED_CHAMBERINREM VARCHAR(500),
							INSPECTED_PASSEDINOB INT,
							INSPECTED_PASSEDINREM VARCHAR(500),
							INSPECTED_FAILEDINOB INT,
							INSPECTED_FAILEDINREM VARCHAR(500),
							
							
							
							CONSTRAINT PK_EARTHELECTRODECHAMBER_ID PRIMARY KEY(EARTHELECTRODECHAMBER_ID),
							CONSTRAINT FK_EARTHELECTRODECHAMBER_EARTHING_ID FOREIGN KEY(EARTHING_ID) REFERENCES earthing_lps_description(EARTHING_ID) ON DELETE CASCADE
							);



				CREATE TABLE earthing_system_table(
							EARTHING_SYSTEM_ID INT AUTO_INCREMENT,
							EARTHING_ID INT,
							FLAG VARCHAR(20),							
							EAST_OB FLOAT,
							EAST_REM VARCHAR(500),
							WEST_OB FLOAT,
							WEST_REM VARCHAR(500),
							NORTH_OB FLOAT,
							NORTH_REM VARCHAR(500),
							SOUTH_OB FLOAT,
							SOUTH_REM VARCHAR(500),
							RINGEARTHWALL_EAST_OB FLOAT,
							RINGEARTHWALL_EAST_REM VARCHAR(500),
							RINGEARTHWALL_WEST_OB FLOAT,
							RINGEARTHWALL_WEST_REM VARCHAR(500),
							RINGEARTHWALL_NORTH_OB FLOAT,
							RINGEARTHWALL_NORTH_REM VARCHAR(500),
							RINGEARTHWALL_SOUTH_OB FLOAT,
							RINGEARTHWALL_SOUTH_REM VARCHAR(500),
							CONNECTED_EARTH_ELECTRODE_OB VARCHAR(225),
							CONNECTED_EARTH_ELECTRODE_REM VARCHAR(500),
							JOINTSMADE_BRAZING_OB VARCHAR(225),
							JOINTSMADE_BRAZING_REM VARCHAR(500),
							MATERIAL_OF_EARTHELECTRODE_OB VARCHAR(225),
							MATERIAL_OF_EARTHELECTRODE_REM VARCHAR(500),
							TYPE_OF_EARTHELECTRODE_OB VARCHAR(225),
							TYPE_OF_EARTHELECTRODE_REM VARCHAR(500),
							SIZE_OFEARTHELECTRODE_OB VARCHAR(225),
							SIZE_OFEARTHELECTRODE_REM VARCHAR(500),
							MAXIMUMDISTANCE_EARTHELECTRODEWAL_OB INT,
							MAXIMUMDISTANCE_EARTHELECTRODEWALL_REM VARCHAR(225),
							MINIMUMDISTANCE_EARTHELECTRODEWALL_OB INT,
							MINIMUMDISTANCE_EARTHELECTRODEWALL_REM VARCHAR(225),
							CONSTRAINT PK_EARTHING_SYSTEM_ID PRIMARY KEY(EARTHING_SYSTEM_ID),
							CONSTRAINT FK_EARTHING_SYSTEM_EARTHING_ID FOREIGN KEY(EARTHING_ID) REFERENCES earthing_lps_description(EARTHING_ID) ON DELETE CASCADE
							);
							
							
				CREATE TABLE earth_electrode_testing(
							EARTH_ELECTRODE_TESTING_ID INT AUTO_INCREMENT,
							EARTHING_ID INT,
							FLAG VARCHAR(20),
							SERIAL_NUMBER INT,
							EARTH_ELECTRODE_TYPE VARCHAR(500),
							EARTH_ELECTRODE_MATERIAL VARCHAR(500),
							EARTH_ELECTRODE_SIZE INT,
							EARTH_ELECTRODE_DEPTH FLOAT,
							EARTH_ELECTRODE_REMARKS VARCHAR(500),
							EARTH_ELECTRODE_RESISTANCE FLOAT,
							
							CONSTRAINT PK_EARTH_ELECTRODE_TESTING_ID PRIMARY KEY(EARTH_ELECTRODE_TESTING_ID),
							CONSTRAINT FK_EARTH_ELECTRODE_TESTING_EARTHING_ID FOREIGN KEY(EARTHING_ID) REFERENCES earthing_lps_description(EARTHING_ID) ON DELETE CASCADE
							);
				 ------>SPD <--------
				 
		  CREATE TABLE spd_report_table(
				            SPD_REPORT_ID INT AUTO_INCREMENT,
				            BASIC_LPS_ID INT,
				            USER_NAME VARCHAR(225),
				            CREATED_BY VARCHAR(255),
						    CREATED_DATE datetime,
						    UPDATED_BY VARCHAR(255),
						    UPDATED_DATE datetime,
				            CONSTRAINT PK_SPD_REPORT_ID  PRIMARY KEY(SPD_REPORT_ID)
				            );
 
          CREATE TABLE spd_table(
				            SPD_ID INT AUTO_INCREMENT,
				            SPD_REPORT_ID INT,				        
				            BUILDING_NUMBER INT,
							BUILDING_NAME VARCHAR(225),
							BUILDING_COUNT INT NOT NULL,
							FLAG VARCHAR(20),
				            MAINS_INCOMING_OB VARCHAR(225),
				            MAINS_INCOMING_REM VARCHAR(225),
				            TOTALMAINS_INCOMING_OB VARCHAR(225),
				            TOTALMAINS_INCOMING_REM VARCHAR(225),
				            NO_PANNELSUPPLITTING_OB VARCHAR(225),
				            NO_PANNELSUPPLITTING_REM VARCHAR(225),
				            TOTAL_NO_OUTDOOREQUIPMENT_OB VARCHAR(225),
				            TOTAL_NO_OUTDOOREQUIPMENT_REM VARCHAR(225),
				            CONSTRAINT PK_SPD_ID  PRIMARY KEY(SPD_ID),
				            CONSTRAINT FK_SPD_REPORT_SPD_ID FOREIGN KEY(SPD_REPORT_ID) REFERENCES spd_report_table(SPD_REPORT_ID) ON DELETE CASCADE				            
				            );

           
           CREATE TABLE spd_description_table(
			               SPDDESCRIPTION_ID INT AUTO_INCREMENT,
			               SPD_ID INT,
			               FLAG VARCHAR(20),
			               LOCATION VARCHAR(225),
			               PANEL_NAME VARCHAR(225),
			               SPD_MAKE_OBSERVATION VARCHAR(225),
			               SPD_MAKE_REMARKS VARCHAR(500),
			               SPD_MODEL_OBSERVATION VARCHAR(225),
			               SPD_MODEL_REMARKS VARCHAR(500),
			               SPD_CLASS_TYPE_OBSERVATION VARCHAR(225),
			               SPD_CLASS_TYPE_REMARKS VARCHAR(500),
			               SPD_APPLICATION_OBSERVATION VARCHAR(225),
			               SPD_APPLICATION_REMARKS VARCHAR(500),
			               SPD_MAIN_APPLICATION_OBSERVATION VARCHAR(225),
			               SPD_MAIN_APPLICATION_REMARKS VARCHAR(500),
			               PROPERCONNECTION_OBSERVATION VARCHAR(225),
			               PROPERCONNECTION_REMARKS VARCHAR(500),
			               INCOMER_RATING_OBSERVATION INT,
			               INCOMER_RATING_REMARKS VARCHAR(500),
			               FUSE_BACKUP_OBSERVATION INT,
			               FUSE_BACKUP_REMARKS VARCHAR(500),
			               CONNECTING_WIRE_LENGTH_PHASE_OBSERVATION FLOAT,
			               CONNECTING_WIRE_LENGTH_PHASE_REMARKS VARCHAR(500),
			               CONNECTING_WIRE_LENGTH_PROTECTIVE_OBSERVATION FLOAT,
			               CONNECTING_WIRE_LENGTH_PROTECTIVE_REMARKS VARCHAR(500),
			               CONNECTING_WIRE_SIZE_PHASE_OBSERVATION FLOAT,
			               CONNECTING_WIRE_SIZE_PHASE_REMARKS VARCHAR(500),
			               CONNECTING_WIRE_SIZE_PROTECTIVE_OBSERVATION FLOAT,
			               CONNECTING_WIRE_SIZE_PROTECTIVE_REMARKS VARCHAR(500),
			               
			               CONSTRAINT PK_SPDDESCRIPTION_ID  PRIMARY KEY(SPDDESCRIPTION_ID),
			               CONSTRAINT FK_SPD_ID FOREIGN KEY(SPD_ID) REFERENCES spd_table(SPD_ID) ON DELETE CASCADE
			        );

							
		 -----------> LPS  SEPARATE-DISTANCE-TABLE <----------	
			
			CREATE TABLE seperation_distance_report_table(
		                SEPERATION_DISTANCE_REPORT_ID INT AUTO_INCREMENT,
		                BASIC_LPS_ID  VARCHAR(225),
		                USER_NAME  VARCHAR(225),
		                CREATED_BY VARCHAR(255),
			            CREATED_DATE datetime,
			            UPDATED_BY VARCHAR(255),
			            UPDATED_DATE datetime,
		                CONSTRAINT PK_SEPERATION_DISTANCE_REPORT_ID  PRIMARY KEY(SEPERATION_DISTANCE_REPORT_ID)
		
		);
						
			CREATE TABLE seperation_distance_table(
		                SEPERATION_DISTANCE_ID INT AUTO_INCREMENT,
		                SEPERATION_DISTANCE_REPORT_ID INT,
		                BUILDING_NUMBER INT,
						BUILDING_NAME VARCHAR(225),
						BUILDING_COUNT INT NOT NULL,
						FLAG VARCHAR(20),
						CALCULATED_SEPERATION_DISTANCE_OB VARCHAR(225),
						CALCULATED_SEPERATION_DISTANCE_REM VARCHAR(500),
		                CONSTRAINT PK_SEPERATION_DISTANCE_ID  PRIMARY KEY(SEPERATION_DISTANCE_ID),
		                CONSTRAINT FK_SEPERATION_DISTANCE_REPORT_SEPERATION_DISTANCE_ID FOREIGN KEY(SEPERATION_DISTANCE_REPORT_ID) REFERENCES seperation_distance_report_table(SEPERATION_DISTANCE_REPORT_ID) ON DELETE CASCADE
		                					
		);


            CREATE TABLE seperation_distance_description_table(
	                    SEPERATION_DISTANCE_DESC_ID INT AUTO_INCREMENT,
	                    SEPERATION_DISTANCE_ID  INT,
						FLAG VARCHAR(20),
	                    SEPERATION_DISTANCE_DESC VARCHAR(225),
	                    SEPERATION_DISTANCE_OB FLOAT,
	                    SEPERATION_DISTANCE_REM VARCHAR(500),
	                    CONSTRAINT PK_SEPERATION_DISTANCE_DESC_ID  PRIMARY KEY(SEPERATION_DISTANCE_DESC_ID),
	                    CONSTRAINT FK_SEPERATION_DISTANCE_ID FOREIGN KEY(SEPERATION_DISTANCE_ID) REFERENCES seperation_distance_table(SEPERATION_DISTANCE_ID) ON DELETE CASCADE
         );
         
         CREATE TABLE seperation_distance_down_conductors_table(
	                    SEPERATION_DISTANCE_DOWN_CONDUCTOR_ID INT AUTO_INCREMENT,
	                    SEPERATION_DISTANCE_ID  INT,
						FLAG VARCHAR(20),
	                    SEPERATION_DISTANCE_DESC VARCHAR(225),
	                    SEPERATION_DISTANCE_OB FLOAT,
	                    SEPERATION_DISTANCE_REM VARCHAR(500),
	                    CONSTRAINT PK_SEPERATION_DISTANCE_DOWN_CONDUCTOR_ID  PRIMARY KEY(SEPERATION_DISTANCE_DOWN_CONDUCTOR_ID),
	                    CONSTRAINT FK_SEPERATION_DISTANCE_DOWN_CONDUCTOR_SEPERATION_DISTANCE_ID FOREIGN KEY(SEPERATION_DISTANCE_ID) REFERENCES seperation_distance_table(SEPERATION_DISTANCE_ID) ON DELETE CASCADE
         );
						
         
         --------->LPS  EARTHSTUD<--------
         
        CREATE TABLE earth_stud_report_table(
			            EARTH_STUD_REPORT_ID INT AUTO_INCREMENT,
			            BASIC_LPS_ID INT,
			            USER_NAME VARCHAR(225),			            
			            CREATED_BY VARCHAR(255),
						CREATED_DATE datetime,
					    UPDATED_BY VARCHAR(255),
					    UPDATED_DATE datetime,
			            CONSTRAINT PK_EARTH_STUD_REPORT_ID PRIMARY KEY(EARTH_STUD_REPORT_ID)
           );
 
        CREATE TABLE earth_stud_description(
			            EARTH_STUD_DESC_ID INT AUTO_INCREMENT,	
			            EARTH_STUD_REPORT_ID INT,	
			            BUILDING_NUMBER INT,
						BUILDING_NAME VARCHAR(225),
						BUILDING_COUNT INT NOT NULL,
						FLAG VARCHAR(20),    
						AVAILABLE_EQUIPOTENTIAL_BONDING_OB VARCHAR(225),
						AVAILABLE_EQUIPOTENTIAL_BONDING_REM VARCHAR(500),
						NUMBER_OF_EQUIPOTENTIAL_BONDING_OB VARCHAR(225),
						NUMBER_OF_EQUIPOTENTIAL_BONDING_REM VARCHAR(500),
						SIZE_OF_EARTHING_CONDUCTOR_OB VARCHAR(225),
						SIZE_OF_EARTHING_CONDUCTOR_REM VARCHAR(500),
						CONCEPT_OF_EQUIPOTENTIAL_BONDING_OB VARCHAR(225),
						CONCEPT_OF_EQUIPOTENTIAL_BONDING_REM VARCHAR(500),
						MAINPROTECTIVE_EQUIPOTENTIAL_BONDING_OB VARCHAR(225),
						MAINPROTECTIVE_EQUIPOTENTIAL_BONDING_REM VARCHAR(500),
						SIZE_OF_MAINPROTECTIVE_OB VARCHAR(225),
						SIZE_OF_MAINPROTECTIVE_REM VARCHAR(500),
						SUPPLIMENTARY_MAINPROTECTIVE_OB VARCHAR(225),
						SUPPLIMENTARY_MAINPROTECTIVE_REM VARCHAR(500),
						SIZE_OF_SUPPLIMENTARY_PROTECTIVE_OB VARCHAR(225),
						SIZE_OF_SUPPLIMENTARY_PROTECTIVE_REM VARCHAR(500),						
			            EARTH_STUDVISIBILITYOB VARCHAR(225),
			            EARTH_STUDVISIBILITYREM VARCHAR(500),
			            EARTH_STUDBENDOB VARCHAR(225),
			            EARTH_STUDBENDREM VARCHAR(500),
			            PROPER_BONDINGRAILOB VARCHAR(225),
			            PROPER_BONDINGRAILREM VARCHAR(500),
			            PHYSICAL_DAMAGESTUDOB VARCHAR(225),
			            PHYSICA_LDAMAGESTUDREM VARCHAR(500),
			            CONTINUTY_EXISTAEARTHOB VARCHAR(225),
			            CONTINUTY_EXISTAEARTHREM VARCHAR(500),			            
			            CONSTRAINT PK_EARTH_STUD_DESC_ID PRIMARY KEY(EARTH_STUD_DESC_ID),
			            CONSTRAINT FK_EARTH_STUD_REPORT_EARTH_STUD_DESC_ID FOREIGN KEY(EARTH_STUD_REPORT_ID) REFERENCES earth_stud_report_table(EARTH_STUD_REPORT_ID) ON DELETE CASCADE
			            
           );
           
           
                    --------->SUMMARY<--------
           
           
           
           CREATE TABLE summary_lps_table(
				            SUMMARY_LPS_ID INT AUTO_INCREMENT,
				            BASIC_LPS_ID INT,
				            USER_NAME VARCHAR(225),
				            SUMMARY_DATE VARCHAR(225),
				            INSPECTED_YEAR INT,
				            FLAG VARCHAR(20),
				            CREATED_BY VARCHAR(255),
						    CREATED_DATE datetime,
						    UPDATED_BY VARCHAR(255),
						    UPDATED_DATE datetime,
				            CONSTRAINT PK_SUMMARY_LPS_ID  PRIMARY KEY(SUMMARY_LPS_ID)
				            );
				            
		CREATE TABLE summary_lps_declaration_table(
		               SUMMARY_LPS_DECLARATION_ID INT AUTO_INCREMENT,
		               SUMMARY_LPS_ID INT,
		               DECLARATION_ROLE VARCHAR(225),
		               LOCATION VARCHAR(225),
		               NAME VARCHAR(225),
		               SIGNATURE LONGTEXT,
		               COMPANY VARCHAR(225),
		               POSITION VARCHAR(225),
		               SPD_MODEL_REMARKS VARCHAR(500),
		               ADDRESS VARCHAR(225),
		               DATE VARCHAR(225),
		               
		               CONSTRAINT PK_SUMMARY_LPS_DECLARATION_ID  PRIMARY KEY(SUMMARY_LPS_DECLARATION_ID),
		               CONSTRAINT FK_SUMMARY_LPS_DECLARATION_SUMMARY_LPS_ID FOREIGN KEY(SUMMARY_LPS_ID) REFERENCES summary_lps_table(SUMMARY_LPS_ID) ON DELETE CASCADE
		        );
 
      CREATE TABLE summary_lps_buildings_table(
			            SUMMARY_LPS_BUILDINGS_ID INT AUTO_INCREMENT,
			            SUMMARY_LPS_ID INT,				        
			            BUILDING_NUMBER INT,
						BUILDING_NAME VARCHAR(225),
						BUILDING_COUNT INT NOT NULL,
						FLAG VARCHAR(20),
			            
			            CONSTRAINT PK_SUMMARY_LPS_BUILDINGS_ID  PRIMARY KEY(SUMMARY_LPS_BUILDINGS_ID),
               			CONSTRAINT FK_SUMMARY_LPS_BUILDINGS_SUMMARY_LPS_ID FOREIGN KEY(SUMMARY_LPS_ID) REFERENCES summary_lps_table(SUMMARY_LPS_ID) ON DELETE CASCADE
		);
			
	  CREATE TABLE summary_lps_observation_table(
	               SUMMARY_LPS_OBSERVATION_ID INT AUTO_INCREMENT,
	               SUMMARY_LPS_BUILDINGS_ID INT,
				   REMARKS_ID INT,
				   HEADING_UI VARCHAR(20),
	               OBSERVATION VARCHAR(225),
	               RECOMMENDATION VARCHAR(225),
	               OBSERVATION_COMPONENT_DETAILS VARCHAR(225),
	               
	               CONSTRAINT PK_SUMMARY_LPS_OBSERVATION_ID  PRIMARY KEY(SUMMARY_LPS_OBSERVATION_ID),
	               CONSTRAINT FK_SUMMARY_LPS_OBSERVATION_SUMMARY_LPS_BUILDINGS_ID FOREIGN KEY(SUMMARY_LPS_BUILDINGS_ID) REFERENCES summary_lps_buildings_table(SUMMARY_LPS_BUILDINGS_ID) ON DELETE CASCADE
	        );
	        
	        
-----------> FILE_UPLOAD_TABLE <----------
   CREATE TABLE file_upload_lps_table(
				FILE_ID INT AUTO_INCREMENT,
				FILE_NAME VARCHAR(255),
				LPS_ID INT,
				COMPONENT_NAME VARCHAR(255),
				FILE_TYPE VARCHAR(255),
				FILE_SIZE VARCHAR(220),
				INDEX_NU INT,
				DATA LONGBLOB,
				BUILDING_COUNT INT,
				STATUS VARCHAR(20),
				CONSTRAINT PK_FILE_ID   PRIMARY KEY(FILE_ID)
				)